### ISSUE TITLE
make build fails with "ERROR: Couldn't find env file"

### ISSUE THREAD

**Issue by edmorley** [mozilla/missioncontrol#125]
Following the instructions in README, I ran `yarn install` followed by `make build` however the build expected the `.env` file to already exist, however it's `.gitignore`d and presumably should be copied from `.env-dist` prior to first build.

Perhaps the Makefile build command should do this, or else a `cp .env-dist .env` be added as an extra README step?

**Comment by wlach** [comment]
I think it's best if this is explicitly called out in the README file. Did this in d1eca98d4d3a006895270fbaa9150f4643522470
