### ISSUE TITLE
Use the official Python docker image instead of manually installing

### ISSUE THREAD

**Issue by edmorley** [mozilla/missioncontrol#129]
Currently the app Docker image is based on `debian:jessie` and then manually installs Python 3, which for Jessie is the slightly old Python 3.4.2.

If instead the Dockerfile were changed to use the official Python image:
* the amount of Dockerfile boilerplate could be reduced
* the build time would be quicker
* you'd have much more flexibility in Python version (since you'd no longer be relying on whatever the debian package version was)
* the image will likely also be smaller in size, given the tweaks that they perform in [their Dockerfile](https://github.com/docker-library/python/blob/27516b7347b3236a3accd4b2e1242a53fb54d04c/3.4/jessie/slim/Dockerfile)

For a list of image tags, see:
https://hub.docker.com/r/library/python/

I would recommend the slim variants, for example `python:3.4-slim` (for parity with the current Dockerfile, later you could switch to `3.5-slim` or `3.6-slim`).

**Comment by wlach** [comment]
Done now, thanks for the suggestion!

**Comment by edmorley** [comment]
You're welcome :-)
