### ISSUE TITLE
Try 'docker-compose pull --parallel' to speed up pull times

### ISSUE THREAD

**Issue by edmorley** [mozilla/missioncontrol#130]
I noticed that the various docker images were being pulled sequentially and not in parallel (well to be more specific, each image downloaded its layers in parallel, but didn't start later images until the earlier ones were complete).

Until docker-compose enables `--parallel` by default (docker/compose#4556), it may be worth seeing if there's a speedup by running a `docker-compose pull --parallel` prior to the `docker-compose up` to force the pull to be made in parallel. (I don't think `up` will accept the `--parallel` argument, hence the need to separate out that step).

**Comment by maurodoglio** [comment]
@edmorley thanks for the tip, I didn't know they added a --parallel parameter.

**Comment by theronic** [comment]
docker-compose now shows `WARNING: --parallel option is deprecated and will be removed in future versions.`

**Comment by Kononnable** [comment]
@theronic 
https://github.com/docker/compose/blob/master/CHANGELOG.md#1210-2018-04-10
>docker-compose pull is now performed in parallel by default. You can opt out using the --no-parallel flag. The --parallel flag is now deprecated and will be removed in a future version.
