### ISSUE TITLE
Experiment with using asap's smoothing

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#151]
Stanford has some techniques for smoothing noisy data to generate a signal, looks like the techniques might be useful for mission control:

http://futuredata.stanford.edu/asap/#code

We might be able to just plug their library in, though I'd like to spend some time to understand what it's doing first. Is this something we want in addition to the percentile filtering which was just added?

**Comment by wlach** [comment]
This might be a fun project for a motivated contributor to work on.

**Comment by harshagarwal7272** [comment]
Is this issue still open??

**Comment by wlach** [comment]
Let's close this out for now.
