### ISSUE TITLE
For crash measures, link to crash-stats supersearch query to get information from the detail view

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#162]
It would be great if for crash measures, we could automatically link to a super search with the appropriate values filled in. This would help people more easily drill down into what's behind a specific measure.

We probably want to add some kind of server-side component to the database to make this more easily configurable, but to get things started I would just implement it entirely on the client based on the current state. I would just put the link besides the timezone indication at the bottom:
﻿﻿
![image](https://user-images.githubusercontent.com/20569/32741628-deaf9f92-c874-11e7-8048-b5d54543af7a.png)

By default I would make the query to supersearch correspond to what's currently visible (i.e. if a particular release is visible, include it in the search).

**Comment by armenzg** [comment]
From the screenshot I assume the URL that we should build would look like this (the dates are roughly the last 48 hours):
https://crash-stats.mozilla.com/search/?product=Firefox&version=56.0.2&version=56.0.1&version=56.0&platform=Linux&process_type=content&date=%3E%3D2017-11-11T14%3A28%3A00.000Z&date=%3C2017-11-13T14%3A28%3A25.000Z&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by wlach** [comment]
Yup, that's exactly what I was thinking! At least for a first pass.

**Comment by armenzg** [comment]
https://crash-stats.mozilla.com/search_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform&_facets=signature&date=%3E%3D2017-11-11T14%3A28%3A00.000Z&date=%3C2017-11-13T14%3A28%3A25.000Z&platform=linux&process_type=content&product=Firefox&sort=-date&version=56.0.2&version=57.0&version=Older#facet-signature
https://crash-stats.mozilla.com/search/?product=Firefox&version=56.0.2&version=56.0.1&version=56.0&platform=Linux&process_type=content&date=%3E%3D2017-11-11T14%3A28%3A00.000Z&date=%3C2017-11-13T14%3A28%3A25.000Z&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by armenzg** [comment]
I just read the title of the issue and partly answered my question.
The PR is 99% complete. I just need an answer for this.

Of the measurements below, to which "Process type" should each match to?

You want links for these:
- content_crashes                       --> content
- gmplugin_crashes                    --> plugin?
- main_crashes                           --> ?
- plugin_crashes                         --> plugin
- content_shutdown_crashes    --> content?

But not these:

- browser_shim_usage_blocked
- permissions_sql_corrupted
- defective_permissions_sql_removed
- slow_script_notice_count
- slow_script_page_count

**Comment by wlach** [comment]
Correct. main_crashes would map to "browser". I'm not sure about how the plugin crashes map to the error_aggregates dataset. Maybe we could ask @chutten (if he's not available here, ask him on IRC).

Please go ahead and post your work-to-date to a PR -- I looked quickly at your source code and have a few comments. Just mark it as WIP so someone doesn't automatically merge it.

**Comment by chutten** [comment]
gmplugin_crashes are plugin crashes. content_shutdown_crashes are content-process crashes with the ShutDownKill ipc_channel_error annotation.

**Comment by wlach** [comment]
I think we're good here.
