### ISSUE TITLE
Order of versions in plot should match sidebar

### ISSUE THREAD

**Issue by fbertsch** [mozilla/missioncontrol#167]
Instead, the two orderings of the versions should be the same.

**Comment by fbertsch** [comment]
<img width="475" alt="screen shot 2017-11-17 at 18 11 48" src="https://user-images.githubusercontent.com/20819040/32974357-fd5e5c3e-cbc2-11e7-80b9-8f8f626a50ba.png">

**Comment by fbertsch** [comment]
See that the plot has [56.0.2, 57.0, Older]. The other versions are [57.0, 56.0.2, 56.0.1, 56.0].

**Comment by wlach** [comment]
Good catch!
