### ISSUE TITLE
Add a dashboard with startup crashes

### ISSUE THREAD

**Issue by marco-c** [mozilla/missioncontrol#200]
Startup crashes are the most problematic, we need to monitor them separately from other types of crashes.

**Comment by wlach** [comment]
I don't believe we currently track startup crashes in telemetry-streaming, not sure why not. Will look into it.

**Comment by wlach** [comment]
I filed a bug to get this added to telemetry-streaming: https://bugzilla.mozilla.org/show_bug.cgi?id=1434378

Should be trivial to add to mission control once that's in place.

**Comment by mozillamarcia** [comment]
As discussed at the meeting today, this would be a must have before we move away from AWSY.
