### ISSUE TITLE
usage_khours might be better represented with a logarithmic scale

### ISSUE THREAD

**Issue by marco-c** [mozilla/missioncontrol#201]
Like on https://telemetry.mozilla.org/crashes/.
Maybe it could be log by default with the option to change it to linear.

**Comment by wlach** [comment]
I think we should be able to see how this works by setting y_scale_type="log" somewhere around here:

https://github.com/mozilla/missioncontrol/blob/ed7bc75a206942568651b406cbbfaa1ef96ec131/frontend/ui/detailview.jsx#L583

If you want to try solving this issue, please post a screenshot of how this looks with the windows/release/main_crashes platform/channel/measure combination. We can then figure out whether we want to make this the default or if we want to make it configurable.

**Comment by SJasoria** [comment]
Hi! Can I work on this issue?

**Comment by wlach** [comment]
For sure, give it a try and show us how it looks, per the instructions above.

**Comment by SJasoria** [comment]
I have made some changes to scale y-axis logarithmically. Here are screenshots for windows/browser_shim_usage_blocked. The path windows/release/main_crashes platform/channel/measure didn't seem to work for me.

When the y-axis scale is set to linear:
![linear](https://user-images.githubusercontent.com/11815849/44413463-07841780-a589-11e8-95ca-278b0793eb79.png)

When the y-axis scale is set to log:

![log](https://user-images.githubusercontent.com/11815849/44413486-1a96e780-a589-11e8-8310-4c0b3cb8531d.png)

**Comment by wlach** [comment]
@SJasoria hmm, I think the linear scale is actually a lot more clear. :) The uptake of a new release is much more clear when you view it linearly. I think it's best if we leave things as they are. Thanks for giving this a try, sometimes it's not obvious whether something is better or worse without some exploration.
