### ISSUE TITLE
Please add main + content crashes measurement

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/missioncontrol#203]
I would second marco's request at https://github.com/mozilla/missioncontrol/issues/202#issuecomment-361551807 to add a M+C-S measurement as an additional option.

**Comment by wlach** [comment]
@philipp-sumo -- we should definitely discuss this further, based on my understanding of the data I feel pretty strongly that it's better to look at the content/main crash rates separately as they are fairly distinct entities. I would be interesting in knowing your use case-- is it simply to get an overview of how a particular release is doing?

Shutdown crashes *should* also be tracked as separate from content crashes, at least as I understand it (see #202).

**Comment by philipp-sumo** [comment]
sure, this was recommended by the telemetry team as the best top-line measure to quickly assess the health of a build in terms of stability & the metric we have been going by  and reporting in meetings the last months/years (similarly on the old https://www.arewestableyet.com/ browser+content is the top-line metric).

if agree that there is also value in being able to look at the main & content process crashes in separate, so i certainly won't advocate for removing them :-)

**Comment by mozillamarcia** [comment]
During an IRC discussion today it was mentioned that this is needed for Channel and CF meetings, since we customarily report overall rate per channel. So in the scheme of things we would need to add this to the "higher priority" list of issues.

**Comment by wlach** [comment]
I'm happy to add this derived measure to the dashboard, it's not that complicated to implement.

**Comment by wlach** [comment]
It seems like getting an accurate count of content crashes (as opposed to content + content shutdown crashes) is blocked by this data issue (which may have to do with either the product behavior or how we're aggregating data) https://bugzilla.mozilla.org/show_bug.cgi?id=1413172

Until this is fixed, I'm not sure if we can really be confident that content-content_shutdown yields an accurate number, and thus we're kind of blocked on producing an overall rate too.

**Comment by wlach** [comment]
An alternative approach might be to update error aggregates to make the content crashes measure only reflect non-shutdown content crashes. Then we could just track "main + content" by itself. https://bugzilla.mozilla.org/show_bug.cgi?id=1453485

**Comment by mozillamarcia** [comment]
I am fine with the alternative approach wlach mentions in the last comment - I think we should decide on an approach and go with it ASAP, especially if chutten doesn't have time to work on Bug 1413172.

**Comment by wlach** [comment]
@mozillamarcia yup, I think this is what we're gonna do. @akkomar is on the bug.
