### ISSUE TITLE
Links don't open in a new tab

### ISSUE THREAD

**Issue by lizzard** [mozilla/missioncontrol#207]
I normally would keep the main Mission control tab open (with vertical tab bar) and then open the various views that I want to see underneath it, so they can be folded up and hidden. But, when I am on the main page at https://data-missioncontrol.dev.mozaws.net/#/, and command-click (on a Mac) to open one of the buttons in a new tab, it doesn't do that. This is kind of minor but it can be really useful in my workflow since I'll need to look at many of these pages one after the other.

**Comment by wlach** [comment]
I remember investigating this issue... but I guess I never fixed it. I don't think the solution is all that involved. Probably just a matter of adding an href to the card elements or something similar.

**Comment by wlach** [comment]
Did some digging, this is harder than I thought to do properly. Something like this might work though:

https://ctrlq.org/code/19639-turn-div-clickable-link
