### ISSUE TITLE
Add a link to this repo on the Mission Control page

### ISSUE THREAD

**Issue by lizzard** [mozilla/missioncontrol#208]
I had to go hunting for the github repo to file bugs. It would be nice to have a link to the repo directly from the Mission Control page(s).

**Comment by wlach** [comment]
Good idea. Something similar to Perfherder's/Treeherder's "help" menu would do nicely here:

![image](https://user-images.githubusercontent.com/20569/35827837-7d785eae-0a8b-11e8-9efa-7431cd3e8121.png)

This should be implementable via reactstrap's navbar component: https://reactstrap.github.io/components/navbar/

Relevant area of code is here: https://github.com/mozilla/missioncontrol/blob/8d7926e8ea8e5aca4e383d4e357be81fc98d497a/frontend/ui/dashboard.jsx#L36
