### ISSUE TITLE
The +- number on the summary page is confusing

### ISSUE THREAD

**Issue by lizzard** [mozilla/missioncontrol#209]
On https://data-missioncontrol.dev.mozaws.net/#/beta/mac for example, I don't know what the + or - number means. I think we discussed it but I can't remember if it is standard deviation or confidence interval, or what.

**Comment by lizzard** [comment]
Again maybe this could be a tooltip. Or there could be some explanatory text at the top or bottom of the page. As long as is explained somewhere the user can find it.

**Comment by wlach** [comment]
It is standard deviation, but should be a confidence interval. And 100% agree that we need to explain this better.

Fixing this properly will require changes on both the frontend and backend.

**Comment by wlach** [comment]
I'm going to fix this by taking out the +/-. I haven't been able to figure out a way of displaying this information in a way that adds any useful information / context. I think it is basically a given that the numbers here are very noisy -- the best we can do is help the user of missioncontrol focus on large changes. Arewestableyet didn't attempt to do anything like this, so I don't think this is a regression from that standpoint.
