### ISSUE TITLE
Landing page should show top-level crash rate trends across various channels

### ISSUE THREAD

**Issue by rkothari19** [mozilla/missioncontrol#210]
We need the landing page to look similar to AWSY. Top-level crash rate trends across various channels and for both Desktop, ESR and Fennec

**Comment by wlach** [comment]
Yep, this has always been on my agenda. The original prototype contained a short summary of the status of each channel/platform combination:

![image](https://user-images.githubusercontent.com/20569/35866580-99254460-0b25-11e8-9618-b6c3cc22da4d.png)

**Comment by wlach** [comment]
We may also want to call out when a new release just went out on this view (and how many khours of usage it had?)

**Comment by mozillamarcia** [comment]
I actually think we want to keep the stability information all in one place, like it is in the current AWSY dashboard and maybe have a different view that shows new release information.

**Comment by wlach** [comment]
@mozillamarcia my understanding of the awsy dashboard is that it is only showing data for the latest (or near-latest) releases on each channel?

**Comment by mozillamarcia** [comment]
For the ADI version on the left, it looks as if for beta and release it is actually several versions (for 59 beta it goes all the way back to beta 8 to my current RC that was built if you hover over that part of the table). For release it spans 57.0.3 - 58.0.2. I believe the methodology Robert used is documented here: https://home.kairo.at/blog/2014-04/how_effective_is_the_stability_program

**Comment by wlach** [comment]
Thanks Marcia, that link is helpful.

Trying to think about how to solve this in a holistic way (which will probably mean solving a bunch of issues at more or less the same time). It seems clear that there are a few stability measures that we *really* care about, the rest of the stuff displayed by mission control is much less important. With that in mind, here's what I've been able to come up with for the landing page:

![image](https://user-images.githubusercontent.com/20569/37122224-b0b2e4f6-222d-11e8-9b24-2d69aea384c9.png)

The idea is that people can click through if they want more detail / compare against older versions / see non-crash measures (we may also be able to surface certain types of information via tooltips on this page as well).

**Comment by wlach** [comment]
#242 implements exactly this. No doubt we'll want to tweak the behaviour, but I think we can do that in followups.

**Comment by mozillamarcia** [comment]
Instead of splitting out Mac, Windows and Linux I think what I heard in our team meeting is that we prefer to have one chart similar to how AWSY has it - so overall one set of data for the release range - does that make sense?

I think we also want to include startup crashes in that set, since if that spikes we would definitely want to know about it.

**Comment by wlach** [comment]
@mozillamarcia I have some tweaks in mind to this view, including aggregating the platform-specific results into a single number that you can use in your channel meetings. :) Hopefully will have time to make a PR later today.

Startup crashes are being tracked in #200.
