### ISSUE TITLE
Documentation/Help on what the “measures” mean

### ISSUE THREAD

**Issue by rkothari19** [mozilla/missioncontrol#214]

**Comment by wlach** [comment]
++ important that we fix this somehow.

**Comment by wlach** [comment]
@mreid and I were talking about this. For each measure, we should link to the docs of dataset where we describe that particular measure (currently just error_aggregates). This is mostly a docs.telemetry.mozilla.org issue, once we have information there we can just link to it here.

**Comment by wlach** [comment]
Filed a bug to add documentation on dtmo: https://bugzilla.mozilla.org/show_bug.cgi?id=1438337

**Comment by wlach** [comment]
Have a pull request open for the docs now: https://github.com/mozilla/firefox-data-docs/pull/88

**Comment by wlach** [comment]
I believe the new help menu and measures documentation should cover this. If anything is unclear please file a followup. :)

**Comment by rkothari19** [comment]
This looks good! I think we may need another round of documentation/help update when we do thresholds etc.
