### ISSUE TITLE
add grid lines to graphs 

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/missioncontrol#221]
i think it may be helpful to set the "y_extended_ticks" property in metrics graphics.js to "true" for the graphs that are drawn, in order to get a better visual sense of how the daily up/downs in the graphs relate to each other.

**Comment by wlach** [comment]
Experimented with this, it doesn't really seem to help much for me, but other perspectives welcome:

![image](https://user-images.githubusercontent.com/20569/36699605-2e4a6f2a-1b1b-11e8-8b9c-15e733a20324.png)

**Comment by philipp-sumo** [comment]
imho having some points of reference is an improvement

**Comment by wlach** [comment]
@philipp-sumo On reflection I think you are right, I will make this change.
