### ISSUE TITLE
page turned blank when comparing beta versions by buildid & relative date to release

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/missioncontrol#237]
i wanted to compare the main crash rate of the 3 release candidate builds on the beta channel.
once i switched the dropdown to "relative to release" i ended up with a totally blank page with the following url:
https://data-missioncontrol.dev.mozaws.net/#/beta/windows/main_crashes?timeInterval=0&relative=1&percentile=99&normalized=1&disabledVersions=20180301022608,20180226180053&versionGrouping=buildid

**Comment by wlach** [comment]
Yup, I can reproduce this, hopefully not too difficult to fix.

**Comment by wlach** [comment]
Note that for beta comparisons, #239 gets in the way a bit. I think the mentioned PR should fix this particular issue though.
