### ISSUE TITLE
Show the last few betas for comparison purposes

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/missioncontrol#249]
I think for the beta channel we might want to consider showing the last few individual betas, mostly because I think we can quickly notice if things have gotten worse from beta to beta.

**Comment by wlach** [comment]
There appear to be a few issues with this which I noticed after deploying to staging:

* We're seeing the extra versions in nightly, which we don't want (not sure how this is happening)
* We shouldn't be including point releases lesser than the current active version, as it looks confusing and weird:

![image](https://user-images.githubusercontent.com/20569/42886217-fcb459a6-8a70-11e8-955b-8352737b8e48.png)

Will fix this in a followup later today
