### ISSUE TITLE
Display a combined measurement/rate per channel that covers all platforms

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/missioncontrol#250]
for reporting purposes in the channel meeting and elsewhere it would be good to have a high-level rate displayed on top of the main landing page that represents the particular channel (release/beta/nightly) regardless of the different rates per OS.

it's great to have separate data available for windows, mac & linux though in order to dig deeper into the differences of the various platforms if need be.

**Comment by philipp-sumo** [comment]
this is also happening within the beta channel. 60.0b10 is displayed as older than 60.0b9 at https://data-missioncontrol.dev.mozaws.net/#/beta/windows/main_crashes currently:
![grafik](https://user-images.githubusercontent.com/1524147/38469903-3fb5c7b2-3b5c-11e8-8e4d-bf4d4dc9033d.png)

**Comment by wlach** [comment]
@philipp-sumo that is a seperate issue, see #239

**Comment by philipp-sumo** [comment]
oops sorry, i meant to put it there...
