### ISSUE TITLE
esr versioning mismatch between error_aggregates_v2 and buildhub

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#269]
error_aggregates labels esr versions without the 'esr' as a differentiator, unlike buildhub which does. We need to handle this for esr data to appear in the mission control dashboard.

**Comment by akkomar** [comment]
@wlach are you going to handle this in the UI?

**Comment by wlach** [comment]
@akomar I think for now I will. I'm uncertain if it's worth the complexity to do this in error_aggregates.
