### ISSUE TITLE
Instead of displaying the various crash categories alphabatically.....

### ISSUE THREAD

**Issue by rkothari19** [mozilla/missioncontrol#287]
Let's display crash categories based on importance level, E.g. list them as:
- main_crashes
- content_crashes
- startup_crashes

**Comment by kagehina919** [comment]
@wlach can I take up this issue? What should be the suggested order, if yes?

**Comment by wlach** [comment]
Hi @kagehina919, would be great if you could take this on.

The initial ordering that @rkothari mentioned sounds about right, I'd probably split into two sections:

Crash Measures:
* main_crashes
* content_crashes
* startup_crashes
* gpu_crashes
* content_shutdown_crashes
* gmplugin_crashes
* plugin_crashes

Other:
(just list alphabetically)

I would use an `h3` element for the headings, and then probably pad the tables a little bit so it looks more "sectional". Anyway, we can always adjust a bit after you make some initial modifications.
