### ISSUE TITLE
Add "experiments uptake" API

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/missioncontrol#301]
We need an API to make the [experiments uptake data](https://github.com/mozilla/telemetry-streaming/pull/135) available for use in experimenter et al.

A description of the desired API is in [this doc](https://docs.google.com/document/d/1IRNtQej9yoQl6uSD9THzB-8DQmFA3pXgQK0RAh3C6ks/edit?ts=5afc7772).

**Comment by wlach** [comment]
Proposed approach:

* Add an ExperimentUptakeDatum model to https://github.com/mozilla/missioncontrol/blob/master/missioncontrol/base/models.py (base it off of the existing datum class)
* Add a new etl function to ingest this data from athena and add a management command to run it for debugging purposes. Prior art here: https://github.com/mozilla/missioncontrol/blob/master/missioncontrol/etl/experiment.py and https://github.com/mozilla/missioncontrol/blob/master/missioncontrol/etl/measure.py and https://github.com/mozilla/missioncontrol/tree/master/missioncontrol/etl/management/commands
* Add a new view to query this table at https://github.com/mozilla/missioncontrol/blob/master/missioncontrol/api/views.py
* Write some basic unit tests (as much as is sane to write without blowing your brains out) to test the above based on the prior art here https://github.com/mozilla/missioncontrol/tree/master/tests

**Comment by wlach** [comment]
My understanding is that we made telemetry-streaming post this data directly to test tube, so we don't need to do this in mission control anymore. Hurrah!
