### ISSUE TITLE
Add testing of some the frontend components (especially those formatting/displaying numbers)

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#317]
This week an embarassing bug slipped in where we were showing the incorrect summary rates in the main dashboard views. Our tests to validate data ingestion and server-side apis didn't succeed in catching this because this was entirely a frontend problem.

We should wire up some simple tests for some of the react components (e.g. the summary cards) with [jest](https://jestjs.io/) so this type of error is less likely to occur in the future.

**Comment by kagehina919** [comment]
@wlach, could you please suggest some types of tests that should be written for the summary component to cover the number formattings?

**Comment by wlach** [comment]
@kagehina919 I think your work in #343 covers most of what I was hoping to do here.

It's a smaller thing, but if you have some spare cycles and feel like testing something simple I would take a look at #344. I should have some other things to look at soon too. :)
