### ISSUE TITLE
Show data for at least 4 versions along with "other"

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#320]
Right now we only show data for 2 versions along with other in the detail view. We shouldn't clutter up the graph with 10+ series, but this is excessively low. E.g. here:

![image](https://user-images.githubusercontent.com/20569/44480356-04346e80-a611-11e8-84b5-2e0d0724f6f7.png)

There's no reason we can't show all five visible series on this graph. It would be much more informative.

The coalescing happens around here:

https://github.com/mozilla/missioncontrol/blob/2e33078e75c096a63ca4c7cbb5854e1088ba3dee/frontend/ui/detailview.jsx#L284

Note the magic numbers of "2" and "3". I would define some constants (e.g. `MAX_VISIBLE_SERIES`) in this file:

https://github.com/mozilla/missioncontrol/blob/master/frontend/schema.js

And then import/use them in the file above.

**Comment by wlach** [comment]
@SJasoria this might be a fun one to work on, I promise this would be useful :)

**Comment by SJasoria** [comment]
I'll start working on this

**Comment by mozillamarcia** [comment]
Hello William - Did we make any progress on this one? Thanks.

**Comment by SJasoria** [comment]
Hi
I didn't get a chance to work on this. If it's urgent someone else can take this up. I won't be able to work on it until end of next week.

**Comment by wlach** [comment]
I probably won't have time to work on this until at least then, so please feel free to pick this up still. I'll comment on this bug if the situation changes.
