### ISSUE TITLE
ESR page does not work

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/missioncontrol#321]
https://missioncontrol.telemetry.mozilla.org/#/?channel=esr

All the numbers are set to 0.0

**Comment by wlach** [comment]
Yep something is broken here, will look into it soon.

**Comment by wlach** [comment]
Looking at this now, it seems like the data is not being ingested, but I'm not sure why... the display version data between error aggregates and buildhub seems to match up fine, which was my first theory on what was going wrong. Investigation continues.
