### ISSUE TITLE
63b10 column in crash pages located after beta8

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/missioncontrol#322]
https://missioncontrol.telemetry.mozilla.org/#/beta/windows

~~`We released beta 10 yesterday`~~

Actually, the column is there but located after beta 8, columns should be ordered in natural sorting, so that's still a UX bug as columns are not sorted per release.

**Comment by wlach** [comment]
Right, I noticed this a while back but forgot to fix it. Will try to find a moment to address this, shouldn't be hard.
