### ISSUE TITLE
Versioning information on beta is imprecise

### ISSUE THREAD

**Issue by wlach** [mozilla/missioncontrol#90]
Right now we're only displaying the major part of the version for beta (e.g. "55.0"). Instead it would be better if we had a breakdown by each release (e.g. "55.0b5").

This is an error aggregation issue: https://github.com/mozilla/telemetry-streaming/pull/59

We should probably also figure out how to use the buildid for more precise information for other channels (e.g. nightly), but that's strictly a seperate issue (will file an issue/pr when I figure out what to do).

**Comment by chutten** [comment]
buildid <-> version mappings are being explored in the buildhub project https://github.com/mozilla-services/buildhub/

Might be useful?

**Comment by wlach** [comment]
Played with this a bit. I can get a mapping of build id to beta version by hitting this endpoint:

https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?_limit=1&build.id=%2220170629075044%22&target.channel=%22beta%22&source.product=%22firefox%22

**Comment by wlach** [comment]
This is addressed by #113
